services:
  webtopubuntu:
    image: kasmweb/remmina:aarch64-1.16.1-rolling-weekly
    container_name: WebTopRemmina
    restart: unless-stopped
    shm_size: 1gb
    volumes:
      - webtop_home:/home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LC_ALL=fr_FR.UTF-8
      - TZ=Europe/Paris
      - TITLE=WebtopUbuntu
      - VNC_PW=CHANGEMEONINSTALL
    ports:
      - "6901:6901"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  webtop_home: