services:
  webtopalpine:
    image: kasmweb/alpine-321-desktop:1.17.0-rolling-weekly
    container_name: WebTopAlpine
    restart: unless-stopped
    shm_size: 1gb
    volumes:
      - webtop_home:/home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LC_ALL=fr_FR.UTF-8
      - TZ=Europe/Paris
      - TITLE=WebtopAlpine
      - VNC_PW=CHANGEMEONINSTALL
    ports:
      - "6901:6901"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  webtop_home:


