version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    extra_hosts:
      - "host.docker.internal:host-gateway
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:arm64
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    volumes:
      - openwebui_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  openwebui_data:
    driver: local


